/*
 * LoRaWAN AGT FSP HAL data for VK_RA4M2.
 *
 * The pristine vendor timer-board.c (lorawan/boards/ra2l1ek_sx126x/) refers to
 * `g_timer0_ctrl/cfg` and `g_timer1_ctrl/cfg` symbols that are normally
 * generated by RASC into ra_gen/hal_data.{c,h}. The port's
 * boards/VK_RA4M2/ra_gen/hal_data.c is owned by RASC and we keep it
 * pristine — so this header + lorawan_hal_data.c provide those two
 * AGT instances out-of-tree.
 *
 * Channel binding (Commit 2 of timer-board refactor):
 *   g_timer0  = AGT4 — free-running cycle-end (RP_IT_CAP_CYCLE_SEC count)
 *   g_timer1  = AGT5 — compare-A sub-second alarm (vendor 0xEFFF wrap)
 *
 * The vendor file reads/writes p_reg->AGT16.* on these directly.
 */

#ifndef LORAWAN_HAL_DATA_H
#define LORAWAN_HAL_DATA_H

#include "r_agt.h"

/* The port's RASC-generated hal_data already exports global symbols named
 * `g_timer0_*` / `g_timer1_*` (GPT4 encoder + machine.Timer reservations),
 * with incompatible types (gpt_instance_ctrl_t). To avoid duplicate
 * definitions at link time we expose the LoRaWAN AGT instances under
 * `lw_g_timer0_*` / `lw_g_timer1_*` and use C-preprocessor #defines
 * (below) so that the pristine vendor timer-board.c, which still writes
 * the literal tokens `g_timer0_ctrl` etc., is silently rewritten by the
 * preprocessor when this header is force-included. Other LoRaWAN
 * translation units (lorawan_hal_data.c, lorawan_softreset.c) include
 * this header normally and pick up the same rewrites.
 */
#define g_timer0_ctrl  lw_g_timer0_ctrl
#define g_timer0_cfg   lw_g_timer0_cfg
#define g_timer1_ctrl  lw_g_timer1_ctrl
#define g_timer1_cfg   lw_g_timer1_cfg

#ifdef __cplusplus
extern "C" {
#endif

extern agt_instance_ctrl_t g_timer0_ctrl;
extern const timer_cfg_t   g_timer0_cfg;

extern agt_instance_ctrl_t g_timer1_ctrl;
extern const timer_cfg_t   g_timer1_cfg;

#ifdef __cplusplus
}
#endif

#endif /* LORAWAN_HAL_DATA_H */
