#ifndef MICROPY_INCLUDED_RENESAS_RA_BOARDS_VK_RA6M3_LV_CONF_BOARD_H
#define MICROPY_INCLUDED_RENESAS_RA_BOARDS_VK_RA6M3_LV_CONF_BOARD_H

#include "lv_conf.h"

#undef LV_FONT_MONTSERRAT_8
#define LV_FONT_MONTSERRAT_8 1
#undef LV_FONT_MONTSERRAT_10
#define LV_FONT_MONTSERRAT_10 1
#undef LV_FONT_MONTSERRAT_18
#define LV_FONT_MONTSERRAT_18 1
#undef LV_FONT_MONTSERRAT_20
#define LV_FONT_MONTSERRAT_20 1
#undef LV_FONT_MONTSERRAT_22
#define LV_FONT_MONTSERRAT_22 1
#undef LV_FONT_MONTSERRAT_24
#define LV_FONT_MONTSERRAT_24 1
#undef LV_FONT_MONTSERRAT_26
#define LV_FONT_MONTSERRAT_26 1
#undef LV_FONT_MONTSERRAT_28
#define LV_FONT_MONTSERRAT_28 1
#undef LV_FONT_MONTSERRAT_30
#define LV_FONT_MONTSERRAT_30 1
#undef LV_FONT_MONTSERRAT_32
#define LV_FONT_MONTSERRAT_32 1
#undef LV_FONT_MONTSERRAT_34
#define LV_FONT_MONTSERRAT_34 1
#undef LV_FONT_MONTSERRAT_36
#define LV_FONT_MONTSERRAT_36 1
#undef LV_FONT_MONTSERRAT_38
#define LV_FONT_MONTSERRAT_38 1

#endif
