#ifndef RM_MOTOR_120_CONTROL_SENSORLESS_CFG_H_H_
#define RM_MOTOR_120_CONTROL_SENSORLESS_CFG_H_H_
#ifdef __cplusplus
extern "C" {
#endif
#define RM_MOTOR_120_CONTROL_SENSORLESS_CFG_H_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#ifdef __cplusplus
}
#endif
#endif
