"""Host-side OTA packer for VK_RA6M5.

Reads a raw firmware binary, appends a 64-byte trailer + (optional) 64 B
ECDSA-P256 signature, and writes a `.ota` file.

Usage:

    # unsigned (development):
    python ota_pack.py firmware.bin out.ota --version 1.2.3
    python ota_pack.py firmware.bin out.ota --version 1.2.3 \\
        --build-hash $(git rev-parse --short HEAD)

    # signed:
    python ota_pack.py firmware.bin out.ota --version 1.2.3 \\
        --sign-key ~/.keys/vk_ra6m5_priv.pem
    # extra: emit the matching public key as a C constant for the bootloader
    python ota_pack.py --emit-pubkey-c boot/bootloader_pubkey.h \\
        --sign-key ~/.keys/vk_ra6m5_priv.pem

Trailer / page layout:

    image_size B   firmware bytes
            +0     trailer struct (64 B)
                     0   4    magic = b'OTAV'
                     4   4    version_int (1.2.3 -> 0x010203)
                     8   4    image_size
                    12   4    build_hash
                    16  32    sha256(firmware bytes)
                    48   1    slot_state (0xFF in fresh package)
                    49   1    retry_count (3)
                    50   1    sig_present (0 unsigned / 1 ECDSA-P256)
                    51   1    reserved
                    52  12    version_str ASCII NUL-padded
            +64    optional 64 B ECDSA-P256 raw signature (r || s, 32 B each)
            +128   end (page boundary on device side)

The 64-byte trailer is followed by 64 B of signature when --sign-key
is given.  Total trailer-page = 128 B (one device write page).  When
unsigned, those 64 bytes stay 0xFF on the device's flash.  This means
the on-device `_ota.read_trailer()` is unaffected (it returns the first
64 B); the signature is read separately by the bootloader.
"""
import argparse
import hashlib
import struct
import sys
import os


MAGIC = b"OTAV"
TRAILER_SZ = 64
SIG_SZ     = 64           # ECDSA P-256 raw r||s
PAGE_SZ    = 128          # device flash page; trailer + signature pad here
STATE_EMPTY = 0xFF


def _ver_int(s):
    parts = s.split(".")
    if len(parts) != 3:
        raise ValueError("version must be MAJOR.MINOR.PATCH")
    a, b, c = (int(p) for p in parts)
    if not (0 <= a <= 255 and 0 <= b <= 255 and 0 <= c <= 255):
        raise ValueError("each component must fit in a byte")
    return (a << 16) | (b << 8) | c


def _build_hash_int(s):
    if not s: return 0
    s = s.strip()
    if not s: return 0
    return int(s, 16) & 0xFFFFFFFF


def _build_trailer(version, image_size, build_hash, sha, retry_count, sig_present):
    version_str = version.encode("ascii")[:12]
    version_str = version_str + b"\x00" * (12 - len(version_str))
    return (
        MAGIC +
        struct.pack("<I", _ver_int(version)) +
        struct.pack("<I", image_size) +
        struct.pack("<I", build_hash) +
        sha +
        struct.pack("<BBBB", STATE_EMPTY, retry_count & 0xFF, sig_present & 0xFF, 0) +
        version_str
    )


def _ecdsa_sign(firmware_bytes, sha, key_path):
    """Sign the firmware SHA-256 with ECDSA-P256.  Returns 64 B raw r||s.

    Requires the `cryptography` package.  Reads a PEM private key.
    """
    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import ec, utils
    except ImportError:
        sys.exit("error: --sign-key requires the `cryptography` package")
    with open(key_path, "rb") as f:
        priv = serialization.load_pem_private_key(f.read(), password=None)
    if not isinstance(priv, ec.EllipticCurvePrivateKey) or priv.curve.name != "secp256r1":
        sys.exit("error: signing key must be an ECDSA-P256 (secp256r1) private key")
    der_sig = priv.sign(sha, ec.ECDSA(utils.Prehashed(hashes.SHA256())))
    r, s = utils.decode_dss_signature(der_sig)
    return r.to_bytes(32, "big") + s.to_bytes(32, "big")


def _emit_pubkey_c(key_path, header_path):
    """Extract the public key matching `key_path` and write a C header
    suitable for inclusion in the bootloader.  Encoding: uncompressed
    SEC1 (0x04 || X(32) || Y(32)) — 65 B."""
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError:
        sys.exit("error: --emit-pubkey-c requires the `cryptography` package")
    with open(key_path, "rb") as f:
        priv = serialization.load_pem_private_key(f.read(), password=None)
    pub = priv.public_key()
    pub_bytes = pub.public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint,
    )    # 65 B: 0x04 || X || Y
    assert len(pub_bytes) == 65
    with open(header_path, "w") as f:
        f.write("/* Auto-generated by ota_pack.py — do not edit by hand. */\n")
        f.write("#ifndef VK_RA6M5_OTA_BOOTLOADER_PUBKEY_H\n")
        f.write("#define VK_RA6M5_OTA_BOOTLOADER_PUBKEY_H\n\n")
        f.write("/* secp256r1 public key, SEC1 uncompressed (0x04 || X || Y). */\n")
        f.write("static const unsigned char ota_bootloader_pubkey[65] = {\n   ")
        for i, b in enumerate(pub_bytes):
            f.write(" 0x%02x," % b)
            if (i + 1) % 12 == 0: f.write("\n   ")
        f.write("\n};\n\n#endif\n")
    print("wrote", header_path)


def _gen_keypair(out_path):
    """Generate a fresh ECDSA-P256 keypair and write the private key to
    `out_path` in PEM (PKCS#8, no password).  The public key file is
    written next to it as <out>.pub.pem."""
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError:
        sys.exit("error: --gen-key requires the `cryptography` package")
    priv = ec.generate_private_key(ec.SECP256R1())
    with open(out_path, "wb") as f:
        f.write(priv.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        ))
    pub_path = out_path + ".pub.pem"
    with open(pub_path, "wb") as f:
        f.write(priv.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        ))
    os.chmod(out_path, 0o600) if hasattr(os, "chmod") else None
    print("wrote private key:", out_path)
    print("wrote public  key:", pub_path)


def main():
    ap = argparse.ArgumentParser(description="Pack firmware.bin into an OTA-ready .ota file")
    ap.add_argument("firmware", nargs="?", help="raw firmware (e.g. firmware.bin)")
    ap.add_argument("output",   nargs="?", help="packed .ota file")
    ap.add_argument("--version",     help="MAJOR.MINOR.PATCH")
    ap.add_argument("--build-hash",  default=None)
    ap.add_argument("--retry-count", type=int, default=3)
    ap.add_argument("--sign-key",    help="PEM ECDSA-P256 private key (sec p256r1)")
    ap.add_argument("--emit-pubkey-c",
                    help="(separate mode) write the bootloader pubkey header")
    ap.add_argument("--gen-key",
                    help="(separate mode) generate a fresh ECDSA-P256 keypair")
    args = ap.parse_args()

    if args.gen_key:
        _gen_keypair(args.gen_key)
        return
    if args.emit_pubkey_c:
        if not args.sign_key:
            sys.exit("--emit-pubkey-c requires --sign-key")
        _emit_pubkey_c(args.sign_key, args.emit_pubkey_c)
        return
    if not args.firmware or not args.output or not args.version:
        ap.error("firmware, output and --version are required (unless --gen-key/--emit-pubkey-c)")

    with open(args.firmware, "rb") as f:
        firmware = f.read()
    image_size = len(firmware)
    if image_size == 0:
        sys.exit("error: firmware is empty")
    if image_size > 0x000E0000:
        print("warning: firmware (%d B) exceeds Slot A budget (896 KB)" %
              image_size, file=sys.stderr)

    sha        = hashlib.sha256(firmware).digest()
    build_hash = _build_hash_int(args.build_hash)

    if args.sign_key:
        signature = _ecdsa_sign(firmware, sha, args.sign_key)
        sig_present = 0x01
    else:
        signature = b"\xff" * SIG_SZ
        sig_present = 0x00

    trailer = _build_trailer(args.version, image_size, build_hash, sha,
                             args.retry_count, sig_present)
    assert len(trailer) == TRAILER_SZ

    with open(args.output, "wb") as f:
        f.write(firmware)
        f.write(trailer)
        f.write(signature)        # 64 B (raw r||s if signed; 0xFF*64 if unsigned)

    total = image_size + TRAILER_SZ + SIG_SZ
    print("packed %s  (%d B firmware + %d B trailer + %d B sig = %d B)" %
          (args.output, image_size, TRAILER_SZ, SIG_SZ, total))
    print("  version    : %s  (0x%06x)" % (args.version, _ver_int(args.version)))
    print("  build_hash : 0x%08x" % build_hash)
    print("  sha256     : %s" % sha.hex())
    print("  retry_count: %d" % args.retry_count)
    print("  signed     : %s" % ("yes" if sig_present else "no (sig_present=0)"))


if __name__ == "__main__":
    main()
