CMSIS_MCU = RA6M2
MCU_SERIES = m4
LD_FILES = boards/EK_RA4M2/ra6m2_ek.ld

# MicroPython settings
MICROPY_VFS_FAT = 1

CFLAGS+=-DDEFAULT_DBG_CH=0 \
          -DCFG_TUD_MAX_SPEED=OPT_MODE_FULL_SPEED \
          -DCFG_TUSB_RHPORT0_MODE=OPT_MODE_DEVICE \
          -DBOARD_TUD_MAX_SPEED=OPT_MODE_FULL_SPEED \
          -DCFG_TUSB_MCU=OPT_MCU_RAXXX \
          -DBOARD_TUD_RHPORT=0
