"""Reproduce the Q15 analytic voice FIR; stdout only, or --check the header.

255-tap Blackman-windowed complex bandpass, Fs=12 kHz, centre=1650 Hz,
prototype cutoff=1500 Hz. USB passes positive audio frequencies; LSB conjugates.
Design method: https://www.dsprelated.com/freebooks/sasp/Hilbert_Transform_Design_Example.html
No SciPy/runtime dependency. Coefficients reside in code flash, not the heap.
"""
import argparse
import math
from pathlib import Path


def header():
    count, delay, rate = 255, 127, 12000
    real, imag = [], []
    for k in range(count):
        t = k - delay
        low = .25 if t == 0 else math.sin(2 * math.pi * 1500 * t / rate) / (math.pi * t)
        window = .42 - .5 * math.cos(2 * math.pi * k / (count - 1)) + .08 * math.cos(4 * math.pi * k / (count - 1))
        angle = 2 * math.pi * 1650 * t / rate
        real.append(round(32768 * 2 * low * window * math.cos(angle)))
        imag.append(round(32768 * 2 * low * window * math.sin(angle)))
    # Exactly reject constant microphone bias after priming. Quantisation only.
    real[delay] -= sum(real)
    assert real == real[::-1] and imag == [-v for v in imag[::-1]]
    assert sum(real) == sum(imag) == 0
    # A signed ADC difference is at most 4095. Both Q15 accumulators fit int32.
    assert max(sum(map(abs, real)), sum(map(abs, imag))) * 4095 < 2**31
    lines = ['/* Generated by tests/tx/gen_ssb_coeffs.py; do not hand-edit.',
             ' * Q15 symmetric I / antisymmetric Q; 255 taps, 12 kHz, 300..3000 Hz voice.',
             ' * Only the first half plus centre is stored. USB means I+jQ at +f.',
             ' */']
    for name, data in [('i', real[:128]), ('q', imag[:127])]:
        lines.append('static const int16_t tx_ssb_' + name + '_q15[' + str(len(data)) + '] = {')
        for k in range(0, len(data), 12):
            lines.append('    ' + ', '.join(str(v) for v in data[k:k+12]) + ',')
        lines.append('};')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = header()
    if args.check:
        path = Path(__file__).resolve().parents[2] / 'ra/ra_tx_ssb_coeffs.h'
        assert path.read_text(encoding='utf-8') == expected, 'Regenerate SSB coefficient header'
        print('PASS reproducible SSB coefficients, exact DC zero and accumulator bounds')
    else:
        print(expected, end='')
