/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
* other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
* EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
* SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS
* SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
* this software. By using this software, you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2019-2022 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "profile_cmn/r_ble_serv_common.h"

extern st_ble_gatts_db_cfg_t g_gatt_db_table;

typedef enum
{
    BLE_INVALID_ATTR_HDL = 0x0000,
    BLE_GAP2S_DECL_HDL = 0x0001,
    BLE_GAP2S_AIO_INC_HDL = 0x0002,
    BLE_GAP2S_DEV_NAME_DECL_HDL = 0x0003,
    BLE_GAP2S_DEV_NAME_VAL_HDL = 0x0004,
    BLE_GAP2S_DEV_NAME_SER_CNFG_DESC_HDL = 0x0005,
    BLE_GAP2S_APPEARANCE_DECL_HDL = 0x0006,
    BLE_GAP2S_APPEARANCE_VAL_HDL = 0x0007,
    BLE_GAP2S_PER_PREF_CONN_PARAM_DECL_HDL = 0x0008,
    BLE_GAP2S_PER_PREF_CONN_PARAM_VAL_HDL = 0x0009,
    BLE_GAP2S_CENT_ADDR_RSLV_DECL_HDL = 0x000A,
    BLE_GAP2S_CENT_ADDR_RSLV_VAL_HDL = 0x000B,
    BLE_GAP2S_RSLV_PRIV_ADDR_ONLY_DECL_HDL = 0x000C,
    BLE_GAP2S_RSLV_PRIV_ADDR_ONLY_VAL_HDL = 0x000D,
    BLE_AIOS_DECL_HDL = 0x000E,
    BLE_AIOS_GAP2_INC_HDL = 0x000F,
    BLE_AIOS_DIGITAL_0_DECL_HDL = 0x0010,
    BLE_AIOS_DIGITAL_0_VAL_HDL = 0x0011,
    BLE_AIOS_DIGITAL_0_CLI_CNFG_DESC_HDL = 0x0012,
    BLE_AIOS_DIGITAL_0_CHAR_PRESENTATION_FORMAT_DESC_HDL = 0x0013,
    BLE_AIOS_DIGITAL_0_CHAR_USER_DESCRIPTION_DESC_HDL = 0x0014,
    BLE_AIOS_DIGITAL_0_CHAR_EXTENDED_PROPERTIES_DESC_HDL = 0x0015,
    BLE_AIOS_DIGITAL_0_VAL_TRIGGER_SETTING_DESC_HDL = 0x0016,
    BLE_AIOS_DIGITAL_0_TIME_TRIGGER_SETTING_DESC_HDL = 0x0017,
    BLE_AIOS_DIGITAL_0_NUM_OF_DIGITALS_DESC_HDL = 0x0018,
    BLE_AIOS_DIGITAL_1_DECL_HDL = 0x0019,
    BLE_AIOS_DIGITAL_1_VAL_HDL = 0x001A,
    BLE_AIOS_DIGITAL_1_CLI_CNFG_DESC_HDL = 0x001B,
    BLE_AIOS_DIGITAL_1_CHAR_PRESENTATION_FORMAT_DESC_HDL = 0x001C,
    BLE_AIOS_DIGITAL_1_CHAR_USER_DESCRIPTION_DESC_HDL = 0x001D,
    BLE_AIOS_DIGITAL_1_CHAR_EXTENDED_PROPERTIES_DESC_HDL = 0x001E,
    BLE_AIOS_DIGITAL_1_VAL_TRIGGER_SETTING_DESC_HDL = 0x001F,
    BLE_AIOS_DIGITAL_1_TIME_TRIGGER_SETTING_DESC_HDL = 0x0020,
    BLE_AIOS_DIGITAL_1_NUM_OF_DIGITALS_DESC_HDL = 0x0021,
    BLE_AIOS_ANALOG_0_DECL_HDL = 0x0022,
    BLE_AIOS_ANALOG_0_VAL_HDL = 0x0023,
    BLE_AIOS_ANALOG_0_CLI_CNFG_DESC_HDL = 0x0024,
    BLE_AIOS_ANALOG_0_CHAR_PRESENTATION_FORMAT_DESC_HDL = 0x0025,
    BLE_AIOS_ANALOG_0_CHAR_USER_DESCRIPTION_DESC_HDL = 0x0026,
    BLE_AIOS_ANALOG_0_CHAR_EXTENDED_PROPERTIES_DESC_HDL = 0x0027,
    BLE_AIOS_ANALOG_0_VAL_TRIGGER_SETTING_DESC_HDL = 0x0028,
    BLE_AIOS_ANALOG_0_TIME_TRIGGER_SETTING_DESC_HDL = 0x0029,
    BLE_AIOS_ANALOG_0_VALID_RANGE_DESC_HDL = 0x002A,
    BLE_AIOS_ANALOG_1_DECL_HDL = 0x002B,
    BLE_AIOS_ANALOG_1_VAL_HDL = 0x002C,
    BLE_AIOS_ANALOG_1_CLI_CNFG_DESC_HDL = 0x002D,
    BLE_AIOS_ANALOG_1_CHAR_PRESENTATION_FORMAT_DESC_HDL = 0x002E,
    BLE_AIOS_ANALOG_1_CHAR_USER_DESCRIPTION_DESC_HDL = 0x002F,
    BLE_AIOS_ANALOG_1_CHAR_EXTENDED_PROPERTIES_DESC_HDL = 0x0030,
    BLE_AIOS_ANALOG_1_VAL_TRIGGER_SETTING_DESC_HDL = 0x0031,
    BLE_AIOS_ANALOG_1_TIME_TRIGGER_SETTING_DESC_HDL = 0x0032,
    BLE_AIOS_ANALOG_1_VALID_RANGE_DESC_HDL = 0x0033,
    BLE_AIOS_AGGREGATE_DECL_HDL = 0x0034,
    BLE_AIOS_AGGREGATE_VAL_HDL = 0x0035,
    BLE_AIOS_AGGREGATE_CLI_CNFG_DESC_HDL = 0x0036,
} e_ble_attr_hdl_t;

#define BLE_GAP2S_DEV_NAME_LEN (128)
#define BLE_GAP2S_DEV_NAME_SER_CNFG_LEN (2)
#define BLE_GAP2S_APPEARANCE_LEN (2)
#define BLE_GAP2S_PER_PREF_CONN_PARAM_LEN (8)
#define BLE_GAP2S_CENT_ADDR_RSLV_LEN (1)
#define BLE_GAP2S_RSLV_PRIV_ADDR_ONLY_LEN (1)
#define BLE_AIOS_DIGITAL_0_LEN (2)
#define BLE_AIOS_DIGITAL_0_CLI_CNFG_LEN (2)
#define BLE_AIOS_DIGITAL_0_CHAR_PRESENTATION_FORMAT_LEN (7)
#define BLE_AIOS_DIGITAL_0_CHAR_USER_DESCRIPTION_LEN (100)
#define BLE_AIOS_DIGITAL_0_CHAR_EXTENDED_PROPERTIES_LEN (2)
#define BLE_AIOS_DIGITAL_0_VAL_TRIGGER_SETTING_LEN (3)
#define BLE_AIOS_DIGITAL_0_TIME_TRIGGER_SETTING_LEN (4)
#define BLE_AIOS_DIGITAL_0_NUM_OF_DIGITALS_LEN (1)
#define BLE_AIOS_DIGITAL_1_LEN (2)
#define BLE_AIOS_DIGITAL_1_CLI_CNFG_LEN (2)
#define BLE_AIOS_DIGITAL_1_CHAR_PRESENTATION_FORMAT_LEN (7)
#define BLE_AIOS_DIGITAL_1_CHAR_USER_DESCRIPTION_LEN (100)
#define BLE_AIOS_DIGITAL_1_CHAR_EXTENDED_PROPERTIES_LEN (2)
#define BLE_AIOS_DIGITAL_1_VAL_TRIGGER_SETTING_LEN (3)
#define BLE_AIOS_DIGITAL_1_TIME_TRIGGER_SETTING_LEN (4)
#define BLE_AIOS_DIGITAL_1_NUM_OF_DIGITALS_LEN (1)
#define BLE_AIOS_ANALOG_0_LEN (2)
#define BLE_AIOS_ANALOG_0_CLI_CNFG_LEN (2)
#define BLE_AIOS_ANALOG_0_CHAR_PRESENTATION_FORMAT_LEN (7)
#define BLE_AIOS_ANALOG_0_CHAR_USER_DESCRIPTION_LEN (20)
#define BLE_AIOS_ANALOG_0_CHAR_EXTENDED_PROPERTIES_LEN (2)
#define BLE_AIOS_ANALOG_0_VAL_TRIGGER_SETTING_LEN (5)
#define BLE_AIOS_ANALOG_0_TIME_TRIGGER_SETTING_LEN (4)
#define BLE_AIOS_ANALOG_0_VALID_RANGE_LEN (4)
#define BLE_AIOS_ANALOG_1_LEN (2)
#define BLE_AIOS_ANALOG_1_CLI_CNFG_LEN (2)
#define BLE_AIOS_ANALOG_1_CHAR_PRESENTATION_FORMAT_LEN (7)
#define BLE_AIOS_ANALOG_1_CHAR_USER_DESCRIPTION_LEN (20)
#define BLE_AIOS_ANALOG_1_CHAR_EXTENDED_PROPERTIES_LEN (2)
#define BLE_AIOS_ANALOG_1_VAL_TRIGGER_SETTING_LEN (5)
#define BLE_AIOS_ANALOG_1_TIME_TRIGGER_SETTING_LEN (4)
#define BLE_AIOS_ANALOG_1_VALID_RANGE_LEN (4)
#define BLE_AIOS_AGGREGATE_LEN (8)
#define BLE_AIOS_AGGREGATE_CLI_CNFG_LEN (2)

#endif /* GATT_DB_H */
