#include <stddef.h>
#include "py/runtime.h"  // For mp_printf debug

// Debug counter for direct ISR hits on IRQ8 (BLE RF)
volatile uint32_t g_irq8_isr_direct_hits = 0;

/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2025 Damien P. George
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 * FSP BLE Compact Library Configuration
 *
 * This file provides the configuration symbols required by the prebuilt
 * FSP BLE Compact library (libr_ble.a). These symbols are normally generated
 * by e2 studio / FSP Configurator but we define them manually here.
 *
 * Reference: Renesas FSP BLE documentation and example projects
 */

#include <stdint.h>
#include <stdbool.h>
#include "r_ble_api.h"
// BLE stack configuration (generated by FSP Configurator in board ra_cfg/)
#include "r_ble_cfg.h"

// Timer instance required by rf_cmt.o inside Renesas BLE compact library.
// We provide an AGT-based timer instance and a small API compatibility shim.
#include "r_timer_api.h"
#include "r_agt.h"

// BLE Abstraction Layer (RM_BLE_ABS)
#include "rm_ble_abs.h"
#include "rm_ble_abs_api.h"

// HAL data for timer and flash instances
#include "hal_data.h"

// For RA4W1 BLE RF interrupt wiring (ICU IRQ8 is reserved for BLE middleware).
#include "common_data.h"
#include "vector_data.h"

// Use MicroPython's lightweight ICU IRQ dispatcher (ports/renesas-ra/ra/ra_icu.c)
// instead of pulling in the full FSP ICU external_irq driver.
#include "ra_icu.h"
#include "r_external_irq_api.h"
#include "r_ble_api.h"  // For st_ble_rf_notify_t
#include "r_ble_cfg.h"  // For BLE_CFG_* macros

// BLE Connection Configuration
// NOTE: The prebuilt Renesas BLE library reads these symbols using 16-bit loads (LDRH),
// so they must be 16-bit wide to avoid picking up stray bytes from adjacent data.
const uint16_t g_ble_conn_max = BLE_CFG_RF_CONNECTION_MAXIMUM;
const uint16_t g_ble_conn_data_max = BLE_CFG_RF_CONNECTION_DATA_MAXIMUM;

// BLE Host Connection Configuration structure
// This is used by R_BLE_GAP_Init to configure the host stack
typedef struct {
    uint8_t conn_max;
    uint16_t mtu_max;
    uint8_t tx_buffer_count;
    uint8_t rx_buffer_count;
} st_ble_host_conn_config_t;

const st_ble_host_conn_config_t ble_host_conn_config = {
    .conn_max = 1,
    .mtu_max = 247,
    .tx_buffer_count = 4,
    .rx_buffer_count = 4,
};

// BLE Controller Connection Entity storage
// Size: approximately 32 bytes per connection (minimal)
static uint8_t s_ble_cntl_conn_ent_storage[32];
uint8_t *g_ble_cntl_conn_ent = s_ble_cntl_conn_ent_storage;

// BLE Controller Heap (main heap for BLE stack)
// Size: 1KB (minimal for basic advertising)
static uint8_t s_ble_cntl_heap_storage[1024];
uint8_t *g_ble_cntl_heap = s_ble_cntl_heap_storage;

// BLE Controller Heap 2 (secondary heap)
static uint8_t s_ble_cntl_heap2_storage[256];
uint8_t *g_ble_cntl_heap2 = s_ble_cntl_heap2_storage;

// BLE Controller Data storage
static uint8_t s_ble_cntl_data_storage[64];
uint8_t *g_ble_cntl_data = s_ble_cntl_data_storage;

// ---------------------------------------------------------------------------
// MINT buffer management heap
// ---------------------------------------------------------------------------
// The Renesas BLE compact library's mint_buf_mgmt_pl_init() expects the
// application to provide a writable heap buffer via g_mint_buf_mgmt_heap_memory.
// If left NULL, mint_buf_mgmt_malloc() will dereference 0x00000000 and HardFault.
//
// Use BLE_CFG_TOTAL_HEAP_SIZE as the default sizing knob (r_ble_cfg.h).
#ifndef BLE_CFG_TOTAL_HEAP_SIZE
#define BLE_CFG_TOTAL_HEAP_SIZE (8192)
#endif

static uint8_t s_mint_buf_mgmt_heap_storage[BLE_CFG_TOTAL_HEAP_SIZE] __attribute__((aligned(4)));

// Provided by the prebuilt Renesas BLE library (libr_ble.a).
extern uint8_t * g_mint_buf_mgmt_heap_memory;

// BLE RF Notify structure (called by RF driver for power management)
// Set enable to 0 to disable all RF event notifications
const st_ble_rf_notify_t g_ble_rf_notify = {
    .enable = 0,      // Disable all RF event notifications
    .start_cb = NULL,
    .close_cb = NULL,
    .dsleep_cb = NULL,
};

// BLE External IRQ instance (for RF interrupt handling)
// libr_ble.a expects this to point at a valid external_irq_instance_t that opens ICU channel 8.
// We provide a small external_irq API wrapper backed by MicroPython's ra_icu dispatcher so:
//  - IRQ8 uses the existing r_icu_isr vector handler (from ra_icu.c)
//  - we don't pull in lib/fsp/.../r_icu.c (whose ISR expects an FSP context pointer)
extern void r_ble_icu_intout_interrupt(void);

// IRQ8 hit counter - incremented every time RF INTOUT fires
extern volatile uint32_t g_irq8_hits;

static void ra_ble_rf_intout_callback(external_irq_callback_args_t * p_args)
{
    (void) p_args;
    g_irq8_hits++;
    r_ble_icu_intout_interrupt();
}

typedef struct
{
    bool open;
    uint8_t channel;
    uint8_t ipl;
    IRQn_Type irq;
    external_irq_trigger_t trigger;
    void (* p_callback)(external_irq_callback_args_t * p_args);
    void const * p_context;
    external_irq_callback_args_t * p_callback_memory;
    external_irq_callback_args_t cb_args;
} ra_ble_external_irq_ctrl_t;

// Debug counter for callback hits
volatile uint32_t g_icu_cb_entered = 0;
volatile uint32_t g_icu_cb_calling_user = 0;
volatile uint32_t g_icu_cb_done = 0;

static void ra_ble_external_irq_icu_cb(void * p_param)
{
    g_icu_cb_entered++;

    ra_ble_external_irq_ctrl_t * p_ctrl = (ra_ble_external_irq_ctrl_t *)p_param;
    if ((NULL == p_ctrl) || (!p_ctrl->open) || (NULL == p_ctrl->p_callback))
    {
        return;
    }

    external_irq_callback_args_t * p_args = p_ctrl->p_callback_memory;
    if (NULL == p_args)
    {
        p_args = &p_ctrl->cb_args;
    }
    p_args->p_context = p_ctrl->p_context;
    p_args->channel   = p_ctrl->channel;

    g_icu_cb_calling_user++;
    p_ctrl->p_callback(p_args);
    g_icu_cb_done++;
}

static fsp_err_t ra_ble_external_irq_open(external_irq_ctrl_t * const p_api_ctrl, external_irq_cfg_t const * const p_cfg)
{
    ra_ble_external_irq_ctrl_t * p_ctrl = (ra_ble_external_irq_ctrl_t *)p_api_ctrl;

    mp_printf(&mp_plat_print, "[IRQ8] open() called, channel=%d, irq=%d\n",
              (int)p_cfg->channel, (int)p_cfg->irq);

    FSP_ASSERT(NULL != p_ctrl);
    FSP_ASSERT(NULL != p_cfg);

    p_ctrl->channel          = p_cfg->channel;
    p_ctrl->ipl              = p_cfg->ipl;
    p_ctrl->irq              = p_cfg->irq;
    p_ctrl->trigger          = p_cfg->trigger;
    p_ctrl->p_callback       = p_cfg->p_callback;
    p_ctrl->p_context        = p_cfg->p_context;
    p_ctrl->p_callback_memory = NULL;
    p_ctrl->open             = true;

    // Configure trigger for ICU IRQ line.
    ra_icu_trigger_irq_no(p_ctrl->channel, (uint32_t)p_ctrl->trigger);

    // Register callback with the MicroPython ICU dispatcher.
    ra_icu_set_callback(p_ctrl->channel, ra_ble_external_irq_icu_cb, p_ctrl);


    // BLE RF INT must not be debounced (default ICU debounce is for mechanical switches).
    ra_icu_set_bounce(p_ctrl->channel, 0);

    // Configure NVIC priority if this IRQ is present in the vector table.
    // CRITICAL: Follow safe enable sequence to prevent immediate IRQ fire
    if (p_ctrl->irq >= 0)
    {
        IRQn_Type irqn = (IRQn_Type)p_ctrl->irq;

        // Step 1: Disable IRQ first (in case it was enabled from previous attempt)
        NVIC_DisableIRQ(irqn);
        mp_printf(&mp_plat_print, "[IRQ8] NVIC disabled for IRQ %d\n", (int)p_ctrl->irq);

        // Step 2: Clear any pending IRQ in NVIC
        NVIC_ClearPendingIRQ(irqn);
        mp_printf(&mp_plat_print, "[IRQ8] NVIC pending cleared for IRQ %d\n", (int)p_ctrl->irq);

        // Step 3: Clear ICU IRQSTn flag (IR bit) - critical for RA MCUs
        // NOTE: We must NOT modify IELSR here because RF library does a write-then-readback
        // verification on IELSR and expects the exact value it wrote. Any modification
        // between RF library's write and readback causes 0xFF03 error.
        // The IR flag will be cleared by R_BSP_IrqStatusClear() later.
        mp_printf(&mp_plat_print, "[IRQ8] IELSR[%d]=0x%08lX (not modified - RF lib will configure)\n",
                  (int)p_ctrl->irq, (unsigned long)R_ICU->IELSR[p_ctrl->irq]);

        // Step 4: Configure priority (callback already registered above via ra_icu_set_callback)
        R_BSP_IrqCfg(irqn, p_ctrl->ipl, (void *)NULL);
        mp_printf(&mp_plat_print, "[IRQ8] Priority configured for IRQ %d\n", (int)p_ctrl->irq);

        // Step 5: Enable the IRQ LAST - after callback is registered and pending is cleared
        R_BSP_IrqEnable(irqn);
        mp_printf(&mp_plat_print, "[IRQ8] NVIC enabled for IRQ %d\n", (int)p_ctrl->irq);
    }

    mp_printf(&mp_plat_print, "[IRQ8] open() returning FSP_SUCCESS\n");
    return FSP_SUCCESS;
}

static fsp_err_t ra_ble_external_irq_enable(external_irq_ctrl_t * const p_api_ctrl)
{
    ra_ble_external_irq_ctrl_t * p_ctrl = (ra_ble_external_irq_ctrl_t *)p_api_ctrl;

    mp_printf(&mp_plat_print, "[IRQ8] enable() called\n");

    FSP_ASSERT(NULL != p_ctrl);
    FSP_ERROR_RETURN(p_ctrl->open, FSP_ERR_NOT_OPEN);
    FSP_ERROR_RETURN(p_ctrl->irq >= 0, FSP_ERR_IRQ_BSP_DISABLED);

    R_BSP_IrqStatusClear(p_ctrl->irq);
    R_BSP_IrqEnable(p_ctrl->irq);

    mp_printf(&mp_plat_print, "[IRQ8] enable() done, NVIC enabled for IRQ %d\n", (int)p_ctrl->irq);

    return FSP_SUCCESS;
}

static fsp_err_t ra_ble_external_irq_disable(external_irq_ctrl_t * const p_api_ctrl)
{
    ra_ble_external_irq_ctrl_t * p_ctrl = (ra_ble_external_irq_ctrl_t *)p_api_ctrl;

    FSP_ASSERT(NULL != p_ctrl);
    FSP_ERROR_RETURN(p_ctrl->open, FSP_ERR_NOT_OPEN);
    FSP_ERROR_RETURN(p_ctrl->irq >= 0, FSP_ERR_IRQ_BSP_DISABLED);

    R_BSP_IrqDisable(p_ctrl->irq);

    return FSP_SUCCESS;
}

static fsp_err_t ra_ble_external_irq_callback_set(external_irq_ctrl_t * const          p_api_ctrl,
                                                  void (                             * p_callback)(external_irq_callback_args_t *),
                                                  void const * const                   p_context,
                                                  external_irq_callback_args_t * const p_callback_memory)
{
    ra_ble_external_irq_ctrl_t * p_ctrl = (ra_ble_external_irq_ctrl_t *)p_api_ctrl;

    FSP_ASSERT(NULL != p_ctrl);
    FSP_ERROR_RETURN(p_ctrl->open, FSP_ERR_NOT_OPEN);

    p_ctrl->p_callback        = p_callback;
    p_ctrl->p_context         = p_context;
    p_ctrl->p_callback_memory = p_callback_memory;

    return FSP_SUCCESS;
}

static fsp_err_t ra_ble_external_irq_close(external_irq_ctrl_t * const p_api_ctrl)
{
    ra_ble_external_irq_ctrl_t * p_ctrl = (ra_ble_external_irq_ctrl_t *)p_api_ctrl;

    FSP_ASSERT(NULL != p_ctrl);
    if (p_ctrl->open)
    {
        if (p_ctrl->irq >= 0)
        {
            R_BSP_IrqDisable(p_ctrl->irq);
        }
        ra_icu_set_callback(p_ctrl->channel, NULL, NULL);
        p_ctrl->open = false;
    }

    return FSP_SUCCESS;
}

static const external_irq_api_t g_ra_ble_external_irq_on_icu =
{
    .open        = ra_ble_external_irq_open,
    .enable      = ra_ble_external_irq_enable,
    .disable     = ra_ble_external_irq_disable,
    .callbackSet = ra_ble_external_irq_callback_set,
    .close       = ra_ble_external_irq_close,
};

static ra_ble_external_irq_ctrl_t g_ble_external_irq8_ctrl;

static const external_irq_cfg_t g_ble_external_irq8_cfg =
{
    .channel       = 8,
    .ipl           = 12,
    .irq           = VECTOR_NUMBER_ICU_IRQ8,
    .trigger       = EXTERNAL_IRQ_TRIG_RISING,
    .pclk_div      = EXTERNAL_IRQ_PCLK_DIV_BY_1,
    .filter_enable = false,
    .p_callback    = ra_ble_rf_intout_callback,
    .p_context     = NULL,
    .p_extend      = NULL,
};

const external_irq_instance_t g_ble_external_irq8 =
{
    .p_ctrl = &g_ble_external_irq8_ctrl,
    .p_cfg  = &g_ble_external_irq8_cfg,
    .p_api  = &g_ra_ble_external_irq_on_icu,
};

// ----------------------------------------------------------------------------
// IMPORTANT: These two global symbols are consumed by the prebuilt BLE library.
// We observed that the RAM location of these pointers is overwritten at runtime
// (e.g. g_ble_external_irq at 0x20000100 becomes 0x20000328), which causes
// HardFault in r_rf_intout_init() when it dereferences p_api->open.
//
// Fix: place the pointers in a NOLOAD/noinit section and set them explicitly
// just before BLE initialization (and optionally re-assert periodically).
// ----------------------------------------------------------------------------
#if defined(__GNUC__)
#define RA_BLE_NOINIT __attribute__((section(".ble_noinit"), used))
#else
#define RA_BLE_NOINIT
#endif

RA_BLE_NOINIT external_irq_instance_t const * g_ble_external_irq;

// BLE Platform Timer instance (for BLE timing)
// The prebuilt BLE compact library (rf_cmt.o) expects `g_ble_pl_timer` to be a
// global variable holding a pointer to an FSP-like timer instance.
//
// NOTE: rf_cmt.o uses a slightly different `timer_api_t` layout (it reads the
// close() function pointer at offset 0x30). To keep compatibility, we create a
// shim API structure with an extra reserved word before close().

extern void r_rf_host_timer_interrupt(void);

volatile uint32_t g_ble_timer_isr_count = 0;

static void ra_ble_pl_timer_callback(timer_callback_args_t * p_args)
{
    (void) p_args;
    g_ble_timer_isr_count++;
    r_rf_host_timer_interrupt();
}

typedef struct st_ra_ble_timer_api_compat
{
    fsp_err_t (* open)(timer_ctrl_t * const p_ctrl, timer_cfg_t const * const p_cfg);
    fsp_err_t (* start)(timer_ctrl_t * const p_ctrl);
    fsp_err_t (* stop)(timer_ctrl_t * const p_ctrl);
    fsp_err_t (* reset)(timer_ctrl_t * const p_ctrl);
    fsp_err_t (* enable)(timer_ctrl_t * const p_ctrl);
    fsp_err_t (* disable)(timer_ctrl_t * const p_ctrl);
    fsp_err_t (* periodSet)(timer_ctrl_t * const p_ctrl, uint32_t const period);
    fsp_err_t (* dutyCycleSet)(timer_ctrl_t * const p_ctrl, uint32_t const duty_cycle_counts, uint32_t const pin);
    fsp_err_t (* infoGet)(timer_ctrl_t * const p_ctrl, timer_info_t * const p_info);
    fsp_err_t (* statusGet)(timer_ctrl_t * const p_ctrl, timer_status_t * const p_status);
    fsp_err_t (* callbackSet)(timer_ctrl_t * const p_api_ctrl,
                              void (* p_callback)(timer_callback_args_t *),
                              void const * const p_context,
                              timer_callback_args_t * const p_callback_memory);
    void const * reserved;
    fsp_err_t (* close)(timer_ctrl_t * const p_ctrl);
} ra_ble_timer_api_compat_t;

static const ra_ble_timer_api_compat_t g_ra_ble_timer_on_agt_compat =
{
    .open         = R_AGT_Open,
    .start        = R_AGT_Start,
    .stop         = R_AGT_Stop,
    .reset        = R_AGT_Reset,
    .enable       = R_AGT_Enable,
    .disable      = R_AGT_Disable,
    .periodSet    = R_AGT_PeriodSet,
    .dutyCycleSet = R_AGT_DutyCycleSet,
    .infoGet      = R_AGT_InfoGet,
    .statusGet    = R_AGT_StatusGet,
    .callbackSet  = R_AGT_CallbackSet,
    .reserved     = NULL,
    .close        = R_AGT_Close,
};

static agt_instance_ctrl_t g_ble_pl_timer_ctrl;

static const agt_extended_cfg_t g_ble_pl_timer_extend =
{
    .count_source = AGT_CLOCK_PCLKB,
    .agto         = AGT_PIN_CFG_DISABLED,
    .agtoab_settings_b.agtoa = AGT_PIN_CFG_DISABLED,
    .agtoab_settings_b.agtob = AGT_PIN_CFG_DISABLED,
    .measurement_mode = AGT_MEASURE_DISABLED,
    .agtio_filter     = AGT_AGTIO_FILTER_NONE,
    .enable_pin       = AGT_ENABLE_PIN_NOT_USED,
    .trigger_edge     = AGT_TRIGGER_EDGE_RISING,
};

static const timer_cfg_t g_ble_pl_timer_cfg =
{
    .mode             = TIMER_MODE_PERIODIC,
    // Initial value is not critical: rf_cmt.o will call periodSet() before start().
    .period_counts    = (uint32_t) 0x10000,
    .source_div       = TIMER_SOURCE_DIV_8,
    .duty_cycle_counts = (uint32_t) 0x8000,
    .channel          = 1,
    .cycle_end_ipl    = 5,
  #if defined(VECTOR_NUMBER_AGT1_INT)
    .cycle_end_irq    = VECTOR_NUMBER_AGT1_INT,
  #else
    .cycle_end_irq    = FSP_INVALID_VECTOR,
  #endif
    .p_callback       = ra_ble_pl_timer_callback,
    .p_context        = NULL,
    .p_extend         = &g_ble_pl_timer_extend,
};

static const timer_instance_t g_ble_pl_timer_inst =
{
    .p_ctrl = &g_ble_pl_timer_ctrl,
    .p_cfg  = &g_ble_pl_timer_cfg,
    .p_api  = (timer_api_t const *) &g_ra_ble_timer_on_agt_compat,
};

RA_BLE_NOINIT timer_instance_t const * g_ble_pl_timer;

// Called from ra_ble.c before RM_BLE_ABS_Open / R_BLE_Open to guarantee that
// the BLE library sees valid platform pointers regardless of earlier RAM writes.
void ra_ble_platform_fixup(void) {
    g_ble_external_irq = &g_ble_external_irq8;
    g_ble_pl_timer     = &g_ble_pl_timer_inst;

    // Provide the heap backing store required by mint_buf_mgmt_pl_init().
    g_mint_buf_mgmt_heap_memory = s_mint_buf_mgmt_heap_storage;
}

// BLE Main Clock frequency in kHz (must match BLE_CFG_MCU_MAIN_CLK_KHZ)
const uint16_t g_ble_main_clk_khz = 8000;  // 8 MHz external crystal

// BLE MCU Clock Change callback
void (*g_ble_mcu_clock_change_fp)(uint32_t) = NULL;

// BLE Device Data Flash addresses (for storing BLE configuration)
const uint32_t g_ble_dev_data_df_addr = 0x40100000;  // Data flash start
const uint32_t g_ble_dev_data_cf_addr = 0x00000000;  // Code flash (not used)

// BLE Debug addresses (for development)
uint8_t g_ble_dbg_rand_addr[6] = {0};
uint8_t g_ble_dbg_pub_addr[6] = {0};

// BLE RF Configuration array (matches Renesas hal_data.c format)
// Byte 0: CLVAL (bits 0-3)
// Byte 1: Slow clock config (EXT32K_EN bit0, MCU_CLKOUT_FREQ bit1, MCU_CLKOUT_PORT bit2, SCA bits4-6)
// Byte 2: Max TX power (bits 0-1)
// Byte 3: RF options (DCDC bit0, DEF_TX_POW bit1, CLKOUT_EN bits4-6)
const uint8_t g_ble_rf_config[] = {
    (BLE_CFG_RF_CLVAL << 0) | 0x00,                             // CLVAL = 6
    (BLE_CFG_RF_EXT32K_EN << 0) |                               // EXT32K = 0
    (BLE_CFG_RF_MCU_CLKOUT_FREQ << 1) |                         // CLKOUT_FREQ = 0
    (BLE_CFG_RF_MCU_CLKOUT_PORT << 2) |                         // CLKOUT_PORT = 0
    (0x01 << 4) |                                                // SCA 151-250 ppm
    0x00,
    (BLE_CFG_RF_MAX_TX_POW << 0) | 0x00,                        // MAX_TX_POW = 1
    (BLE_CFG_RF_DCDC_CONVERTER_ENABLE << 0) |                   // DCDC = 0
    (BLE_CFG_RF_DEF_TX_POW << 1) |                              // DEF_TX_POW = 0
    (BLE_CFG_RF_CLKOUT_EN << 4) |                               // CLKOUT_EN = 0
    0x00
};

// ============================================================================
// GATT Database Configuration (Device Information Service)
// ============================================================================

// UUID table (packed bytes)
// Contains all UUIDs used in GATT database
static const uint8_t g_ble_uuid_table[] = {
    // Offset 0-1: 0x180A (Device Information Service)
    0x0A, 0x18,
    // Offset 2-3: 0x2A29 (Manufacturer Name String)
    0x29, 0x2A,
    // Offset 4-5: 0x2A23 (System ID)
    0x23, 0x2A,
};

// Attribute values (must be defined before attr_cfg)
static uint8_t g_ble_attr_val_table[] = {
    'R', 'e', 'n', 'e', 's', 'a', 's', 0x00,  // Manufacturer Name at offset 0
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,  // System ID at offset 8
};

// Attribute configurations
// Each entry defines one attribute (service or characteristic)
static const st_ble_gatts_db_attr_cfg_t g_ble_attr_cfg[] = {
    // Handle 0: Service declaration (Device Information Service)
    {
        .desc_prop = BLE_GATT_DB_READ,  // Service property
        .next = 0xFFFF,                 // No more attributes with this UUID
        .uuid_offset = 0,               // Points to 0x180A in uuid_table
        .p_data_offset = NULL,          // Service declaration has no value
    },
    // Handle 1: Characteristic (Manufacturer Name String)
    {
        .desc_prop = BLE_GATT_DB_READ,  // Read property
        .next = 0xFFFF,                 // No more attributes with this UUID
        .uuid_offset = 2,               // Points to 0x2A29 in uuid_table
        .p_data_offset = &g_ble_attr_val_table[0],  // Manufacturer Name at offset 0
    },
    // Handle 2: Characteristic (System ID)
    {
        .desc_prop = BLE_GATT_DB_READ,  // Read property
        .next = 0xFFFF,                 // No more attributes with this UUID
        .uuid_offset = 4,               // Points to 0x2A23 in uuid_table
        .p_data_offset = &g_ble_attr_val_table[8],  // System ID at offset 8
    },
};

// UUID configuration (index for fast UUID lookup)
static const st_ble_gatts_db_uuid_cfg_t g_ble_uuid_cfg[] = {
    // UUID 0x180A (Device Information Service)
    {
        .offset = 0,           // Offset in uuid_table
        .first = 0,            // First handle with this UUID
        .last = 0,             // Last handle with this UUID
    },
    // UUID 0x2A29 (Manufacturer Name String)
    {
        .offset = 2,           // Offset in uuid_table
        .first = 1,            // First handle with this UUID
        .last = 1,             // Last handle with this UUID
    },
    // UUID 0x2A23 (System ID)
    {
        .offset = 4,           // Offset in uuid_table
        .first = 2,            // First handle with this UUID
        .last = 2,             // Last handle with this UUID
    },
};

// GATT Database configuration structure
// This is passed to R_BLE_GATTS_SetDbInst() to configure the GATT server
st_ble_gatts_db_cfg_t g_ble_gatts_db_cfg = {
    .p_uuid_table = g_ble_uuid_table,
    .p_attr_val_table = g_ble_attr_val_table,
    .p_const_attr_val_table = NULL,
    .p_rem_spec_val_table = NULL,
    .p_const_rem_spec_val_table = NULL,
    .p_uuid_cfg = g_ble_uuid_cfg,
    .p_attr_cfg = g_ble_attr_cfg,
    .p_char_cfg = NULL,
    .p_serv_cfg = NULL,
    .serv_cnt = 0,
    .char_cnt = 0,
    .uuid_type_cnt = 3,        // Total number of unique UUIDs
    .peer_spec_val_cnt = 0,
};

// ============================================================================
// BLE Abstraction Layer (RM_BLE_ABS) Instance
// ============================================================================

// Forward declaration of GAP callback (defined in ra_ble.c)
extern void ra_ble_abs_gap_callback(uint16_t event_type, ble_status_t event_result, st_ble_evt_data_t *p_event_data);

// BLE ABS control block (initialized by RM_BLE_ABS_Open)
ble_abs_instance_ctrl_t g_ble_abs0_ctrl;

// BLE ABS configuration
const ble_abs_cfg_t g_ble_abs0_cfg =
{
    .channel = 0,
    .gap_callback = ra_ble_abs_gap_callback,
    .vendor_specific_callback = NULL,
    .p_gatt_server_callback_list = NULL,
    .gatt_server_callback_list_number = 0,
    .p_gatt_client_callback_list = NULL,
    .gatt_client_callback_list_number = 0,
    .p_pairing_parameter = NULL,  // No pairing/bonding for now
    .p_flash_instance = &g_flash0,
    .p_timer_instance = &g_timer_ble,
    .p_callback = NULL,
    .p_context = NULL,
    .p_extend = NULL,
};

// BLE ABS instance
const ble_abs_instance_t g_ble_abs0 =
{
    .p_ctrl = &g_ble_abs0_ctrl,
    .p_cfg = &g_ble_abs0_cfg,
    .p_api = &g_ble_abs_on_ble,
};

